/*******************************************************************************
 * JMMC project ( http://www.jmmc.fr ) - Copyright (C) CNRS.
 ******************************************************************************/
package fr.jmmc.oiexplorer.core.gui;

import fr.jmmc.oiexplorer.core.model.plot.Axis;
import fr.jmmc.oiexplorer.core.model.plot.Range;

/**
 * Axis editor widget.
 * 
 * @author mella
 */
public class AxisEditor extends javax.swing.JPanel {
    

    /* members */
    /** TODO previous selection for combo box */
    /** TODO store reference of plotDefinitionEditor for change notifications */
    
    /** Creates new form AxisEditor */
    public AxisEditor() {
        initComponents();
        
    }
    
    /** Initialize widgets according to given axis 
     * 
     * @param axis used to initialize widget states
     */
    public void initForm(Axis axis){   
        includeZeroCheckBox.setSelected(axis.isIncludeZero());
        logScaleCheckBox.setSelected(axis.isLogScale());
        plotErrorCheckBox.setSelected(axis.isPlotError());                
        
        Range range = axis.getRange();
        if(range==null){
            //no range
            rangeCheckBox.setSelected(false);
        }else{
            rangeCheckBox.setSelected(true);
            minSpinner.setValue(range.getMin());
            maxSpinner.setValue(range.getMax());
        }        
    }
    
    /** Set available choices for axis name 
     *  TODO
     */
    public void setAxisChoices(){
        
    }        

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        rangeCheckBox = new javax.swing.JCheckBox();
        nameComboBox = new javax.swing.JComboBox();
        logScaleCheckBox = new javax.swing.JCheckBox();
        includeZeroCheckBox = new javax.swing.JCheckBox();
        plotErrorCheckBox = new javax.swing.JCheckBox();
        minSpinner = new javax.swing.JSpinner();
        maxSpinner = new javax.swing.JSpinner();

        setLayout(new java.awt.GridBagLayout());

        rangeCheckBox.setText("min/max");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 0);
        add(rangeCheckBox, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        add(nameComboBox, gridBagConstraints);

        logScaleCheckBox.setText("log");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        add(logScaleCheckBox, gridBagConstraints);

        includeZeroCheckBox.setText("include 0");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        add(includeZeroCheckBox, gridBagConstraints);

        plotErrorCheckBox.setText("error");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        add(plotErrorCheckBox, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        add(minSpinner, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        add(maxSpinner, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox includeZeroCheckBox;
    private javax.swing.JCheckBox logScaleCheckBox;
    private javax.swing.JSpinner maxSpinner;
    private javax.swing.JSpinner minSpinner;
    private javax.swing.JComboBox nameComboBox;
    private javax.swing.JCheckBox plotErrorCheckBox;
    private javax.swing.JCheckBox rangeCheckBox;
    // End of variables declaration//GEN-END:variables
}
